name: Netikslumas teste [Vilmanto]
description: "Informacijos forma. Apie testo klausimą ar netikslumą kreipkitės tiesiai į dėstytoją per „Teams“."
title: '[testas] Netikslumas (žinutę siųsiu dėstytojui)'
labels: ["Naujas :new:", "Vieta: testai :test_tube:"]
body:
  - type: markdown
    attributes:
      value: |
          # Svarbu

          ***DĖMESIO!!!*** 

          Apie netikslumus TESTUOSE rašykite tiesiai dėstytojui per „Teams“.  
          Šio šablono nepildykite.

          Pateikite:
          1. internetinę klausimo nuorodą (URL) arba testo numerį ir tikslų klausimo tekstą;
          3. ekrano nuotrauką su pažymėta vieta;
          4. netikslų tekstą ir, jei įmanoma, siūlomą taisymą;
          5. trumpą paaiškinimą, jei reikia.

          ***DĖMESIO!!!*** 

  - type: dropdown
    id: course
    attributes:
      label: Dalykas
      options:
        - BS-2026
        - kitas
      default: 0
    validations:
      required: true
  - type: dropdown
    id: teacher
    attributes:
      label: Dėstytojas
      options:
        - Vilmantas
        - Rimantė
        - Justinas
        - Vita
        - kitas
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: sent-to-teacher
    attributes:
      label: Patvirtinimas
      options:
        - label: Šią informaciją ir nusiunčiau ją tiesiai dėstytojui per „Teams“.
          required: true
